//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polarimeter2019.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
            

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("False")]
        private bool IsDemo
        {
            get
            {
                return System.Convert.ToBoolean(this.IsDemo);
            }
            set
            {
                this.IsDemo = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("Red")]
        public global::System.Drawing.Color ReferenceColor
        {
            get
            {
                return (global::System.Drawing.Color)this.ReferenceColor;
            }
            set
            {
                this.ReferenceColor = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("Blue")]
        public global::System.Drawing.Color Color1
        {
            get
            {
                return (global::System.Drawing.Color)this.Color1;
            }
            set
            {
                this.Color1 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("192, 0, 192")]
        public global::System.Drawing.Color Color2
        {
            get
            {
                return (global::System.Drawing.Color)this.Color2;
            }
            set
            {
                this.Color2 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("0, 192, 192")]
        public global::System.Drawing.Color Color3
        {
            get
            {
                return (global::System.Drawing.Color)this.Color3;
            }
            set
            {
                this.Color3 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("64, 64, 64")]
        public global::System.Drawing.Color Color4
        {
            get
            {
                return (global::System.Drawing.Color)this.Color4;
            }
            set
            {
                this.Color4 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("192, 0, 192")]
        public global::System.Drawing.Color Color5
        {
            get
            {
                return (global::System.Drawing.Color)this.Color5;
            }
            set
            {
                this.Color5 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("0, 0, 192")]
        public global::System.Drawing.Color Color6
        {
            get
            {
                return (global::System.Drawing.Color)this.Color6;
            }
            set
            {
                this.Color6 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("0, 192, 192")]
        public global::System.Drawing.Color Color7
        {
            get
            {
                return (global::System.Drawing.Color)this.Color7;
            }
            set
            {
                this.Color7 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("0, 192, 0")]
        public global::System.Drawing.Color Color8
        {
            get
            {
                return (global::System.Drawing.Color)this.Color8;
            }
            set
            {
                this.Color8 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("192, 192, 0")]
        public global::System.Drawing.Color Color9
        {
            get
            {
                return (global::System.Drawing.Color)this.Color9;
            }
            set
            {
                this.Color9 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("192, 64, 0")]
        public global::System.Drawing.Color Color10
        {
            get
            {
                return (global::System.Drawing.Color)this.Color10;
            }
            set
            {
                this.Color10 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("192, 0, 0")]
        public global::System.Drawing.Color Color11
        {
            get
            {
                return (global::System.Drawing.Color)this.Color11;
            }
            set
            {
                this.Color11 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("Gray")]
        public global::System.Drawing.Color Color12
        {
            get
            {
                return (global::System.Drawing.Color)this.Color12;
            }
            set
            {
                this.Color12 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("255, 128, 255")]
        public global::System.Drawing.Color Color13
        {
            get
            {
                return (global::System.Drawing.Color)this.Color13;
            }
            set
            {
                this.Color13 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("128, 128, 255")]
        public global::System.Drawing.Color Color14
        {
            get
            {
                return (global::System.Drawing.Color)this.Color14;
            }
            set
            {
                this.Color14 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("128, 255, 255")]
        public global::System.Drawing.Color Color15
        {
            get
            {
                return (global::System.Drawing.Color)this.Color15;
            }
            set
            {
                this.Color15 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("128, 255, 128")]
        public global::System.Drawing.Color Color16
        {
            get
            {
                return (global::System.Drawing.Color)this.Color16;
            }
            set
            {
                this.Color16 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("255, 255, 128")]
        public global::System.Drawing.Color Color17
        {
            get
            {
                return (global::System.Drawing.Color)this.Color17;
            }
            set
            {
                this.Color17 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("255, 192, 128")]
        public global::System.Drawing.Color Color18
        {
            get
            {
                return (global::System.Drawing.Color)this.Color18;
            }
            set
            {
                this.Color18 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("255, 128, 128")]
        public global::System.Drawing.Color Color19
        {
            get
            {
                return (global::System.Drawing.Color)this.Color19;
            }
            set
            {
                this.Color19 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("Silver")]
        public global::System.Drawing.Color Color20
        {
            get
            {
                return (global::System.Drawing.Color)this.Color20;
            }
            set
            {
                this.Color20 = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("15")]
        public double VoltageRange
        {
            get
            {
                return System.Convert.ToDouble(this.VoltageRange);
            }
            set
            {
                this.VoltageRange = value;
            }
        }

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("0.0001")]
        public double VoltageResolution
        {
            get
            {
                return System.Convert.ToDouble(this.VoltageResolution);
            }
            set
            {
                this.VoltageResolution = value;
            }
        }
    }
}

namespace My
{
    //[global::Microsoft.VisualBasic.HideModuleName()]
    [global::System.Diagnostics.DebuggerNonUserCode()]
    [global::System.Runtime.CompilerServices.CompilerGenerated()]
    internal static class MySettingsProperty
    {
        [global::System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static global::Polarimeter2019.Properties.Settings
            
    }
}

//            get
//            {
                
//                //return global::Polarimeter.My.MySettings.Default;
//            }
//        }
//    }
//}

